version: "3.9"

services:
  coconutclient:
    image: hoanthui123/coconutclient:latest
    ports:
      - "4173:4173"
    environment:
       VITE_API_ENDPOINT: https://api.cococlassroom.online/
       VITE_FILE_HOST: https://file.cococlassroom.online
       VITE_SOCKET_ENDPOINT: wss://socket.cococlassroom.online/
       VITE_NODE_ENV: prod
       VITE_GG_CLIENT_ID: 946931472697-b256pqdojtqjhaeeng9dt4804skb03st.apps.googleusercontent.com
    
  coconutserver:
    image: hoanthui123/coconutserver:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./config/server/application.properties:/app/config/application.properties
      - ./config/server/serviceAccountKey.json:/app/app/serviceAccountKey.json
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - seaweedfs-master
      - seaweedfs-volume
    command:
      - "java"
      - "-jar"
      - "elearning-0.0.1-SNAPSHOT.jar"
      - "--spring.config.location=/app/config/application.properties"

  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=Y3KgattXgebGXUd
    volumes:
      - ./.db/elasticsearch/volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.db/postgres/volume:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: default
      POSTGRES_PASSWORD: 9yEumx4mEb
      POSTGRES_DB: default

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass 9QYVMZNxuSmPp1GyvNs38FKh4rqBMZfCMrCWkXlnmpSm
    ports:
      - "6379:6379"
    volumes:
      - ./.db/redis/volume:/data

  seaweedfs-master:
    image: chrislusf/seaweedfs
    ports:
      - "9333:9333"
      - "19333:19333"
      - "9324:9324"
    volumes:
      - ./.db/seaweedfs-master:/data
    command: "master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324"

  seaweedfs-volume:
    image: chrislusf/seaweedfs
    ports:
      - "8082:8082"
      - "18080:18080"
      - "9325:9325"
    volumes:
      - ./.db/seaweedfs-volume:/data
    command: 'volume -mserver="seaweedfs-master:9333" -ip.bind=0.0.0.0 -port=8082  -metricsPort=9325'
    depends_on:
      - seaweedfs-master